# Generated by Django 5.2.7 on 2025-12-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengaduan',
            old_name='warga',
            new_name='pelapor',
        ),
        migrations.RenameField(
            model_name='pengaduan',
            old_name='tanggal',
            new_name='tanggal_lapor',
        ),
        migrations.RemoveField(
            model_name='pengaduan',
            name='isi',
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='deskripsi',
            field=models.TextField(default='kosong'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(default='Menunggu', max_length=50),
        ),
        migrations.AddField(
            model_name='warga',
            name='nik',
            field=models.CharField(default='dff', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warga',
            name='no_telepon',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='judul',
            field=models.CharField(default='kosong', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warga',
            name='alamat',
            field=models.TextField(default='kosong'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warga',
            name='nama_lengkap',
            field=models.CharField(default='kosong', max_length=100),
            preserve_default=False,
        ),
    ]
