# Generated by Django 5.2.7 on 2025-11-26 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_pengaduan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warga',
            name='nama_lengkap',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='no_telepon',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='tanggal_registrasi',
        ),
        migrations.AddField(
            model_name='warga',
            name='nama',
            field=models.CharField(default='Anonim', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warga',
            name='no_hp',
            field=models.CharField(default='Anonim', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='judul',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='pelapor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warga.warga'),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru'), ('proses', 'Diproses'), ('selesai', 'Selesai')], default='baru', max_length=20),
        ),
        migrations.AlterField(
            model_name='warga',
            name='alamat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='warga',
            name='nik',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
