# Generated by Django 5.2.7 on 2025-11-26 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0003_remove_warga_nama_lengkap_remove_warga_no_telepon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warga',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='no_hp',
        ),
        migrations.AddField(
            model_name='warga',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Lengkap'),
        ),
        migrations.AddField(
            model_name='warga',
            name='no_telepon',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nomor Telepon'),
        ),
        migrations.AddField(
            model_name='warga',
            name='tanggal_registrasi',
            field=models.DateTimeField(auto_now_add=True, default='ddd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='judul',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='pelapor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan', to='warga.warga'),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(choices=[('BARU', 'Baru'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai')], default='BARU', max_length=10),
        ),
        migrations.AlterField(
            model_name='warga',
            name='alamat',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat Tinggal'),
        ),
        migrations.AlterField(
            model_name='warga',
            name='nik',
            field=models.CharField(max_length=16, unique=True, verbose_name='Nomor Induk Kependudukan'),
        ),
    ]
